// @generated by tools/gen-render-native.mjs from client-rs/packages/render-wasm/src/lib.rs — DO NOT EDIT (bun tools/gen-render-native.mjs)
#![allow(clippy::all, clippy::too_many_arguments)]
use crate::wire::{DecodeError, Reader};

/// FNV-1a over the canonical op signatures: the JS proxy sends it in HELLO; a mismatch refuses the stream.
pub const API_HASH: u32 = 0x6265d7f5;
/// Wire opcode of the frame-commit command (JS `render()`).
pub const OP_FRAME_COMMIT: u16 = 80;
pub const OP_COUNT: u16 = 80;

pub type CmdResult = Result<(), String>;

/// One method per render-wasm export (rust name; ids passed in by the JS allocator). No defaults on purpose.
pub trait Commands {
    /// op 1 · JS `createMesh` · allocates a "mesh" id
    fn create_mesh(&mut self, id: u32, positions: &[f32], normals: &[f32], uvs: &[f32], indices: &[u32]) -> CmdResult;
    /// op 2 · JS `destroyMesh`
    fn destroy_mesh(&mut self, id: u32) -> CmdResult;
    /// op 3 · JS `createSkin` · allocates a "skin" id
    fn create_skin(&mut self, id: u32, joint_count: u32, inverse_bind: &[f32]) -> CmdResult;
    /// op 4 · JS `setSkinPose`
    fn set_skin_pose(&mut self, id: u32, joint_matrices: &[f32]) -> CmdResult;
    /// op 5 · JS `destroySkin`
    fn destroy_skin(&mut self, id: u32) -> CmdResult;
    /// op 6 · JS `createSkinnedMesh` · allocates a "mesh" id
    fn create_skinned_mesh(&mut self, id: u32, skin: u32, positions: &[f32], normals: &[f32], uvs: &[f32], joints: &[u32], weights: &[f32], indices: &[u32]) -> CmdResult;
    /// op 7 · JS `destroySkinnedMesh`
    fn destroy_skinned_mesh(&mut self, id: u32) -> CmdResult;
    /// op 8 · JS `createTexture` · allocates a "texture" id
    fn create_texture(&mut self, id: u32, width: u32, height: u32, rgba: &[u8]) -> CmdResult;
    /// op 9 · JS `createTextureCompressed` · allocates a "texture" id
    fn create_texture_compressed(&mut self, id: u32, gl_format: u32, width: u32, height: u32, mip_count: u32, data: &[u8], srgb: bool, flip_y: bool) -> CmdResult;
    /// op 10 · JS `createTextureLinear` · allocates a "texture" id
    fn create_texture_linear(&mut self, id: u32, width: u32, height: u32, rgba: &[u8]) -> CmdResult;
    /// op 11 · JS `createTextureArray` · allocates a "texture" id
    fn create_texture_array(&mut self, id: u32, width: u32, height: u32, layers: u32, rgba: &[u8], srgb: bool) -> CmdResult;
    /// op 12 · JS `createTextureCube` · allocates a "texture" id
    fn create_texture_cube(&mut self, id: u32, size: u32, faces: &[u8], srgb: bool) -> CmdResult;
    /// op 13 · JS `updateTextureLayer`
    fn update_texture_layer(&mut self, id: u32, layer: u32, rgba: &[u8]) -> CmdResult;
    /// op 14 · JS `setMaterialMaps`
    fn set_material_maps(&mut self, id: u32, array: u32, normal: u32, roughness: u32, metalness: u32, emissive: u32, ao: u32, normal_scale: f32, side: u32) -> CmdResult;
    /// op 15 · JS `setMeshUv1`
    fn set_mesh_uv1(&mut self, id: u32, uv1: &[f32]) -> CmdResult;
    /// op 16 · JS `setMeshColors`
    fn set_mesh_colors(&mut self, id: u32, rgba: &[f32]) -> CmdResult;
    /// op 17 · JS `setMaterialFlags`
    fn set_material_flags(&mut self, id: u32, blend: u32, unlit: bool, depth_write: i32, render_order: i32, cast_shadow: i32) -> CmdResult;
    /// op 18 · JS `setMaterialUnlitToneMapped`
    fn set_material_unlit_tone_mapped(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 19 · JS `setMaterialNoReceiveShadow`
    fn set_material_no_receive_shadow(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 20 · JS `setMaterialNoGi`
    fn set_material_no_gi(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 21 · JS `setMaterialChrLight`
    fn set_material_chr_light(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 22 · JS `setMaterialNoFog`
    fn set_material_no_fog(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 23 · JS `setMaterialNoColorWrite`
    fn set_material_no_color_write(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 24 · JS `setMaterialNoDepthTest`
    fn set_material_no_depth_test(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 25 · JS `setMaterialShadowCullBack`
    fn set_material_shadow_cull_back(&mut self, id: u32, on: bool) -> CmdResult;
    /// op 26 · JS `destroyTexture`
    fn destroy_texture(&mut self, id: u32) -> CmdResult;
    /// op 27 · JS `createMaterial` · allocates a "material" id
    fn create_material(&mut self, id: u32, base_color: &[f32], metallic: f32, roughness: f32, base_color_texture: u32, alpha_cutoff: f32, emissive: &[f32]) -> CmdResult;
    /// op 28 · JS `updateMaterial`
    fn update_material(&mut self, id: u32, base_color: &[f32], metallic: f32, roughness: f32, base_color_texture: u32, alpha_cutoff: f32, emissive: &[f32]) -> CmdResult;
    /// op 29 · JS `createShaderMaterial` · allocates a "material" id
    fn create_shader_material(&mut self, id: u32, wgsl: &str, vertex_entry: &str, fragment_entry: &str, bindings: &[gaia_render::MaterialBinding]) -> CmdResult;
    /// op 30 · JS `createThreeMaterial` · allocates a "material" id
    fn create_three_material(&mut self, id: u32, package_json: &str, texture_names: &[String], texture_ids: &[u32]) -> CmdResult;
    /// op 31 · JS `createStorageBuffer` · allocates a "storage" id
    fn create_storage_buffer(&mut self, id: u32, bytes: &[u8]) -> CmdResult;
    /// op 32 · JS `updateStorageBuffer`
    fn update_storage_buffer(&mut self, id: u32, bytes: &[u8]) -> CmdResult;
    /// op 33 · JS `destroyStorageBuffer`
    fn destroy_storage_buffer(&mut self, id: u32) -> CmdResult;
    /// op 34 · JS `bindThreeStorage`
    fn bind_three_storage(&mut self, material: u32, key: &str, id: u32) -> CmdResult;
    /// op 35 · JS `setThreeTime`
    fn set_three_time(&mut self, seconds: f32) -> CmdResult;
    /// op 36 · JS `setThreeUniforms`
    fn set_three_uniforms(&mut self, material: u32, json: &str) -> CmdResult;
    /// op 37 · JS `setThreeUniformsBatch`
    fn set_three_uniforms_batch(&mut self, json: &str) -> CmdResult;
    /// op 38 · JS `setMeshAttribute`
    fn set_mesh_attribute(&mut self, mesh: u32, name: &str, item_size: u32, data: &[f32]) -> CmdResult;
    /// op 39 · JS `setInstanceAttribute`
    fn set_instance_attribute(&mut self, instance: u32, name: &str, item_size: u32, data: &[f32]) -> CmdResult;
    /// op 40 · JS `destroyMaterial`
    fn destroy_material(&mut self, id: u32) -> CmdResult;
    /// op 41 · JS `createInstance` · allocates a "instance" id
    fn create_instance(&mut self, id: u32, mesh: u32, material: u32, mat4: &[f32]) -> CmdResult;
    /// op 42 · JS `updateInstance`
    fn update_instance(&mut self, id: u32, mat4: &[f32]) -> CmdResult;
    /// op 43 · JS `removeInstance`
    fn remove_instance(&mut self, id: u32) -> CmdResult;
    /// op 44 · JS `createInstanceBlock` · allocates a "instance block" id
    fn create_instance_block(&mut self, id: u32, mesh: u32, material: u32, mats: &[f32], colors: &[f32], color_stride: u32, count: u32, world: &[f32]) -> CmdResult;
    /// op 45 · JS `updateInstanceBlock`
    fn update_instance_block(&mut self, id: u32, mats: &[f32], colors: &[f32], color_stride: u32, count: u32, world: &[f32]) -> CmdResult;
    /// op 46 · JS `setInstanceBlockUvs`
    fn set_instance_block_uvs(&mut self, id: u32, uvs: &[f32]) -> CmdResult;
    /// op 47 · JS `setInstanceBlockFlags`
    fn set_instance_block_flags(&mut self, id: u32, cast_shadow: bool, is_static: bool) -> CmdResult;
    /// op 48 · JS `setInstanceBlockShadowOnly`
    fn set_instance_block_shadow_only(&mut self, id: u32, only: bool) -> CmdResult;
    /// op 49 · JS `removeInstanceBlock`
    fn remove_instance_block(&mut self, id: u32) -> CmdResult;
    /// op 50 · JS `setInstanceStatic`
    fn set_instance_static(&mut self, id: u32, is_static: bool) -> CmdResult;
    /// op 51 · JS `setInstanceGroups`
    fn set_instance_groups(&mut self, id: u32, words: &[u32]) -> CmdResult;
    /// op 52 · JS `setInstanceGroupParent`
    fn set_instance_group_parent(&mut self, id: u32, parent: u32) -> CmdResult;
    /// op 53 · JS `setActiveGroups`
    fn set_active_groups(&mut self, words: &[u32]) -> CmdResult;
    /// op 54 · JS `clearActiveGroups`
    fn clear_active_groups(&mut self) -> CmdResult;
    /// op 55 · JS `setInstanceShadowOnly`
    fn set_instance_shadow_only(&mut self, id: u32, only: bool) -> CmdResult;
    /// op 56 · JS `setInstanceCastShadow`
    fn set_instance_cast_shadow(&mut self, id: u32, cast: bool) -> CmdResult;
    /// op 57 · JS `setShadowOptions`
    fn set_shadow_options(&mut self, opts: &serde_json::Value) -> CmdResult;
    /// op 58 · JS `setCamera`
    fn set_camera(&mut self, world: &[f32], yfov: f32, znear: f32, zfar: f32) -> CmdResult;
    /// op 59 · JS `setSun`
    fn set_sun(&mut self, direction: &[f32], color: &[f32], intensity: f32) -> CmdResult;
    /// op 60 · JS `setHemisphereIrradiance`
    fn set_hemisphere_irradiance(&mut self, sky: &[f32], ground: &[f32]) -> CmdResult;
    /// op 61 · JS `setGiProbes`
    fn set_gi_probes(&mut self, irradiance: &[f32], depth: &[f32], params: &[f32]) -> CmdResult;
    /// op 62 · JS `clearGiProbes`
    fn clear_gi_probes(&mut self) -> CmdResult;
    /// op 63 · JS `setFog`
    fn set_fog(&mut self, mode: u32, color: &[f32], near: f32, far: f32, density: f32) -> CmdResult;
    /// op 64 · JS `setEnvironmentSh`
    fn set_environment_sh(&mut self, sh: &[f32], intensity: f32) -> CmdResult;
    /// op 65 · JS `clearEnvironment`
    fn clear_environment(&mut self) -> CmdResult;
    /// op 66 · JS `setBackgroundCube`
    fn set_background_cube(&mut self, size: u32, faces: &[u8], srgb: bool, intensity: f32) -> CmdResult;
    /// op 67 · JS `setBackgroundTexture`
    fn set_background_texture(&mut self, width: u32, height: u32, rgba: &[u8], srgb: bool, equirect: bool, intensity: f32) -> CmdResult;
    /// op 68 · JS `clearBackgroundTexture`
    fn clear_background_texture(&mut self) -> CmdResult;
    /// op 69 · JS `setToneMapping`
    fn set_tone_mapping(&mut self, mode: u32) -> CmdResult;
    /// op 70 · JS `setExposure`
    fn set_exposure(&mut self, e: f32) -> CmdResult;
    /// op 71 · JS `setBloom`
    fn set_bloom(&mut self, strength: f32, radius: f32, threshold: f32, smooth_width: f32) -> CmdResult;
    /// op 72 · JS `setGtao`
    fn set_gtao(&mut self, on: bool, radius: f32, thickness: f32, samples: f32, distance_exponent: f32, distance_fall_off: f32, scale: f32, resolution_scale: f32, intensity: f32, fade_start: f32, fade_end: f32) -> CmdResult;
    /// op 73 · JS `setColorGrade`
    fn set_color_grade(&mut self, m: &[f32]) -> CmdResult;
    /// op 74 · JS `setAutoExposure`
    fn set_auto_exposure(&mut self, on: bool, mul: f32) -> CmdResult;
    /// op 75 · JS `setBackgroundColor`
    fn set_background_color(&mut self, rgb: &[f32]) -> CmdResult;
    /// op 76 · JS `setClearColor`
    fn set_clear_color(&mut self, rgba: &[f32]) -> CmdResult;
    /// op 77 · JS `setPointLights`
    fn set_point_lights(&mut self, packed: &[f32]) -> CmdResult;
    /// op 78 · JS `setExtraDirs`
    fn set_extra_dirs(&mut self, packed: &[f32]) -> CmdResult;
    /// op 79 · JS `setRenderHeight`
    fn set_render_height(&mut self, h: u32) -> CmdResult;
    /// op 80 · JS `render`
    fn frame_commit(&mut self) -> CmdResult;
    // ---- queries (read once per frame commit into the report; JS getters serve the cached value) ----
    /// JS `compressedStats`
    fn compressed_stats(&mut self) -> serde_json::Value;
    /// JS `threeSkipped`
    fn three_skipped(&mut self) -> serde_json::Value;
    /// JS `drawnInstanceCount`
    fn drawn_instance_count(&mut self) -> serde_json::Value;
    /// JS `instanceCount`
    fn instance_count(&mut self) -> serde_json::Value;
    /// JS `lastGroupHidden`
    fn last_group_hidden(&mut self) -> serde_json::Value;
    /// JS `shadowStats`
    fn shadow_stats(&mut self) -> serde_json::Value;
    /// JS `autoExposureGrid` (drain: value is consumed by this call)
    fn auto_exposure_grid(&mut self) -> serde_json::Value;
    /// JS `hdrScene`
    fn hdr_scene(&mut self) -> serde_json::Value;
    /// JS `passStats`
    fn pass_stats(&mut self) -> serde_json::Value;
    /// JS `drawCalls`
    fn draw_calls(&mut self) -> serde_json::Value;
    /// JS `hasTimestamps`
    fn has_timestamps(&mut self) -> serde_json::Value;
    /// JS `sizes`
    fn sizes(&mut self) -> serde_json::Value;
}

pub fn op_name(op: u16) -> &'static str {
    match op {
        1 => "createMesh",
        2 => "destroyMesh",
        3 => "createSkin",
        4 => "setSkinPose",
        5 => "destroySkin",
        6 => "createSkinnedMesh",
        7 => "destroySkinnedMesh",
        8 => "createTexture",
        9 => "createTextureCompressed",
        10 => "createTextureLinear",
        11 => "createTextureArray",
        12 => "createTextureCube",
        13 => "updateTextureLayer",
        14 => "setMaterialMaps",
        15 => "setMeshUv1",
        16 => "setMeshColors",
        17 => "setMaterialFlags",
        18 => "setMaterialUnlitToneMapped",
        19 => "setMaterialNoReceiveShadow",
        20 => "setMaterialNoGi",
        21 => "setMaterialChrLight",
        22 => "setMaterialNoFog",
        23 => "setMaterialNoColorWrite",
        24 => "setMaterialNoDepthTest",
        25 => "setMaterialShadowCullBack",
        26 => "destroyTexture",
        27 => "createMaterial",
        28 => "updateMaterial",
        29 => "createShaderMaterial",
        30 => "createThreeMaterial",
        31 => "createStorageBuffer",
        32 => "updateStorageBuffer",
        33 => "destroyStorageBuffer",
        34 => "bindThreeStorage",
        35 => "setThreeTime",
        36 => "setThreeUniforms",
        37 => "setThreeUniformsBatch",
        38 => "setMeshAttribute",
        39 => "setInstanceAttribute",
        40 => "destroyMaterial",
        41 => "createInstance",
        42 => "updateInstance",
        43 => "removeInstance",
        44 => "createInstanceBlock",
        45 => "updateInstanceBlock",
        46 => "setInstanceBlockUvs",
        47 => "setInstanceBlockFlags",
        48 => "setInstanceBlockShadowOnly",
        49 => "removeInstanceBlock",
        50 => "setInstanceStatic",
        51 => "setInstanceGroups",
        52 => "setInstanceGroupParent",
        53 => "setActiveGroups",
        54 => "clearActiveGroups",
        55 => "setInstanceShadowOnly",
        56 => "setInstanceCastShadow",
        57 => "setShadowOptions",
        58 => "setCamera",
        59 => "setSun",
        60 => "setHemisphereIrradiance",
        61 => "setGiProbes",
        62 => "clearGiProbes",
        63 => "setFog",
        64 => "setEnvironmentSh",
        65 => "clearEnvironment",
        66 => "setBackgroundCube",
        67 => "setBackgroundTexture",
        68 => "clearBackgroundTexture",
        69 => "setToneMapping",
        70 => "setExposure",
        71 => "setBloom",
        72 => "setGtao",
        73 => "setColorGrade",
        74 => "setAutoExposure",
        75 => "setBackgroundColor",
        76 => "setClearColor",
        77 => "setPointLights",
        78 => "setExtraDirs",
        79 => "setRenderHeight",
        80 => "render",
        _ => "?",
    }
}

/// Result of one decoded command: `id` = the handle the command carried (creates) else 0.
pub struct Dispatched {
    pub id: u32,
    pub result: CmdResult,
}

/// Decode one command payload (header already stripped) and invoke the matching `Commands` method.
/// `Err(DecodeError)` = payload malformed / unknown op (the command is skipped; framing is intact).
pub fn dispatch<C: Commands + ?Sized>(c: &mut C, op: u16, r: &mut Reader<'_>) -> Result<Dispatched, DecodeError> {
    Ok(match op {
        1 => {
            let id = r.u32()?;
            let positions = r.f32s()?;
            let normals = r.f32s()?;
            let uvs = r.f32s()?;
            let indices = r.u32s()?;
            Dispatched { id: id, result: c.create_mesh(id, &positions, &normals, &uvs, &indices) }
        }
        2 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.destroy_mesh(id) }
        }
        3 => {
            let id = r.u32()?;
            let joint_count = r.u32()?;
            let inverse_bind = r.f32s()?;
            Dispatched { id: id, result: c.create_skin(id, joint_count, &inverse_bind) }
        }
        4 => {
            let id = r.u32()?;
            let joint_matrices = r.f32s()?;
            Dispatched { id: 0, result: c.set_skin_pose(id, &joint_matrices) }
        }
        5 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.destroy_skin(id) }
        }
        6 => {
            let id = r.u32()?;
            let skin = r.u32()?;
            let positions = r.f32s()?;
            let normals = r.f32s()?;
            let uvs = r.f32s()?;
            let joints = r.u32s()?;
            let weights = r.f32s()?;
            let indices = r.u32s()?;
            Dispatched { id: id, result: c.create_skinned_mesh(id, skin, &positions, &normals, &uvs, &joints, &weights, &indices) }
        }
        7 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.destroy_skinned_mesh(id) }
        }
        8 => {
            let id = r.u32()?;
            let width = r.u32()?;
            let height = r.u32()?;
            let rgba = r.u8s()?;
            Dispatched { id: id, result: c.create_texture(id, width, height, &rgba) }
        }
        9 => {
            let id = r.u32()?;
            let gl_format = r.u32()?;
            let width = r.u32()?;
            let height = r.u32()?;
            let mip_count = r.u32()?;
            let data = r.u8s()?;
            let srgb = r.bool()?;
            let flip_y = r.bool()?;
            Dispatched { id: id, result: c.create_texture_compressed(id, gl_format, width, height, mip_count, &data, srgb, flip_y) }
        }
        10 => {
            let id = r.u32()?;
            let width = r.u32()?;
            let height = r.u32()?;
            let rgba = r.u8s()?;
            Dispatched { id: id, result: c.create_texture_linear(id, width, height, &rgba) }
        }
        11 => {
            let id = r.u32()?;
            let width = r.u32()?;
            let height = r.u32()?;
            let layers = r.u32()?;
            let rgba = r.u8s()?;
            let srgb = r.bool()?;
            Dispatched { id: id, result: c.create_texture_array(id, width, height, layers, &rgba, srgb) }
        }
        12 => {
            let id = r.u32()?;
            let size = r.u32()?;
            let faces = r.u8s()?;
            let srgb = r.bool()?;
            Dispatched { id: id, result: c.create_texture_cube(id, size, &faces, srgb) }
        }
        13 => {
            let id = r.u32()?;
            let layer = r.u32()?;
            let rgba = r.u8s()?;
            Dispatched { id: 0, result: c.update_texture_layer(id, layer, &rgba) }
        }
        14 => {
            let id = r.u32()?;
            let array = r.u32()?;
            let normal = r.u32()?;
            let roughness = r.u32()?;
            let metalness = r.u32()?;
            let emissive = r.u32()?;
            let ao = r.u32()?;
            let normal_scale = r.f32()?;
            let side = r.u32()?;
            Dispatched { id: 0, result: c.set_material_maps(id, array, normal, roughness, metalness, emissive, ao, normal_scale, side) }
        }
        15 => {
            let id = r.u32()?;
            let uv1 = r.f32s()?;
            Dispatched { id: 0, result: c.set_mesh_uv1(id, &uv1) }
        }
        16 => {
            let id = r.u32()?;
            let rgba = r.f32s()?;
            Dispatched { id: 0, result: c.set_mesh_colors(id, &rgba) }
        }
        17 => {
            let id = r.u32()?;
            let blend = r.u32()?;
            let unlit = r.bool()?;
            let depth_write = r.i32()?;
            let render_order = r.i32()?;
            let cast_shadow = r.i32()?;
            Dispatched { id: 0, result: c.set_material_flags(id, blend, unlit, depth_write, render_order, cast_shadow) }
        }
        18 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_unlit_tone_mapped(id, on) }
        }
        19 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_no_receive_shadow(id, on) }
        }
        20 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_no_gi(id, on) }
        }
        21 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_chr_light(id, on) }
        }
        22 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_no_fog(id, on) }
        }
        23 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_no_color_write(id, on) }
        }
        24 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_no_depth_test(id, on) }
        }
        25 => {
            let id = r.u32()?;
            let on = r.bool()?;
            Dispatched { id: 0, result: c.set_material_shadow_cull_back(id, on) }
        }
        26 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.destroy_texture(id) }
        }
        27 => {
            let id = r.u32()?;
            let base_color = r.f32s()?;
            let metallic = r.f32()?;
            let roughness = r.f32()?;
            let base_color_texture = r.u32()?;
            let alpha_cutoff = r.f32()?;
            let emissive = r.f32s()?;
            Dispatched { id: id, result: c.create_material(id, &base_color, metallic, roughness, base_color_texture, alpha_cutoff, &emissive) }
        }
        28 => {
            let id = r.u32()?;
            let base_color = r.f32s()?;
            let metallic = r.f32()?;
            let roughness = r.f32()?;
            let base_color_texture = r.u32()?;
            let alpha_cutoff = r.f32()?;
            let emissive = r.f32s()?;
            Dispatched { id: 0, result: c.update_material(id, &base_color, metallic, roughness, base_color_texture, alpha_cutoff, &emissive) }
        }
        29 => {
            let id = r.u32()?;
            let wgsl = r.str()?;
            let vertex_entry = r.str()?;
            let fragment_entry = r.str()?;
            let bindings = r.bindings()?;
            Dispatched { id: id, result: c.create_shader_material(id, wgsl, vertex_entry, fragment_entry, &bindings) }
        }
        30 => {
            let id = r.u32()?;
            let package_json = r.str()?;
            let texture_names = r.strlist()?;
            let texture_ids = r.u32s()?;
            Dispatched { id: id, result: c.create_three_material(id, package_json, &texture_names, &texture_ids) }
        }
        31 => {
            let id = r.u32()?;
            let bytes = r.u8s()?;
            Dispatched { id: id, result: c.create_storage_buffer(id, &bytes) }
        }
        32 => {
            let id = r.u32()?;
            let bytes = r.u8s()?;
            Dispatched { id: 0, result: c.update_storage_buffer(id, &bytes) }
        }
        33 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.destroy_storage_buffer(id) }
        }
        34 => {
            let material = r.u32()?;
            let key = r.str()?;
            let id = r.u32()?;
            Dispatched { id: 0, result: c.bind_three_storage(material, key, id) }
        }
        35 => {
            let seconds = r.f32()?;
            Dispatched { id: 0, result: c.set_three_time(seconds) }
        }
        36 => {
            let material = r.u32()?;
            let json = r.str()?;
            Dispatched { id: 0, result: c.set_three_uniforms(material, json) }
        }
        37 => {
            let json = r.str()?;
            Dispatched { id: 0, result: c.set_three_uniforms_batch(json) }
        }
        38 => {
            let mesh = r.u32()?;
            let name = r.str()?;
            let item_size = r.u32()?;
            let data = r.f32s()?;
            Dispatched { id: 0, result: c.set_mesh_attribute(mesh, name, item_size, &data) }
        }
        39 => {
            let instance = r.u32()?;
            let name = r.str()?;
            let item_size = r.u32()?;
            let data = r.f32s()?;
            Dispatched { id: 0, result: c.set_instance_attribute(instance, name, item_size, &data) }
        }
        40 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.destroy_material(id) }
        }
        41 => {
            let id = r.u32()?;
            let mesh = r.u32()?;
            let material = r.u32()?;
            let mat4 = r.f32s()?;
            Dispatched { id: id, result: c.create_instance(id, mesh, material, &mat4) }
        }
        42 => {
            let id = r.u32()?;
            let mat4 = r.f32s()?;
            Dispatched { id: 0, result: c.update_instance(id, &mat4) }
        }
        43 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.remove_instance(id) }
        }
        44 => {
            let id = r.u32()?;
            let mesh = r.u32()?;
            let material = r.u32()?;
            let mats = r.f32s()?;
            let colors = r.f32s()?;
            let color_stride = r.u32()?;
            let count = r.u32()?;
            let world = r.f32s()?;
            Dispatched { id: id, result: c.create_instance_block(id, mesh, material, &mats, &colors, color_stride, count, &world) }
        }
        45 => {
            let id = r.u32()?;
            let mats = r.f32s()?;
            let colors = r.f32s()?;
            let color_stride = r.u32()?;
            let count = r.u32()?;
            let world = r.f32s()?;
            Dispatched { id: 0, result: c.update_instance_block(id, &mats, &colors, color_stride, count, &world) }
        }
        46 => {
            let id = r.u32()?;
            let uvs = r.f32s()?;
            Dispatched { id: 0, result: c.set_instance_block_uvs(id, &uvs) }
        }
        47 => {
            let id = r.u32()?;
            let cast_shadow = r.bool()?;
            let is_static = r.bool()?;
            Dispatched { id: 0, result: c.set_instance_block_flags(id, cast_shadow, is_static) }
        }
        48 => {
            let id = r.u32()?;
            let only = r.bool()?;
            Dispatched { id: 0, result: c.set_instance_block_shadow_only(id, only) }
        }
        49 => {
            let id = r.u32()?;
            Dispatched { id: 0, result: c.remove_instance_block(id) }
        }
        50 => {
            let id = r.u32()?;
            let is_static = r.bool()?;
            Dispatched { id: 0, result: c.set_instance_static(id, is_static) }
        }
        51 => {
            let id = r.u32()?;
            let words = r.u32s()?;
            Dispatched { id: 0, result: c.set_instance_groups(id, &words) }
        }
        52 => {
            let id = r.u32()?;
            let parent = r.u32()?;
            Dispatched { id: 0, result: c.set_instance_group_parent(id, parent) }
        }
        53 => {
            let words = r.u32s()?;
            Dispatched { id: 0, result: c.set_active_groups(&words) }
        }
        54 => {
            Dispatched { id: 0, result: c.clear_active_groups() }
        }
        55 => {
            let id = r.u32()?;
            let only = r.bool()?;
            Dispatched { id: 0, result: c.set_instance_shadow_only(id, only) }
        }
        56 => {
            let id = r.u32()?;
            let cast = r.bool()?;
            Dispatched { id: 0, result: c.set_instance_cast_shadow(id, cast) }
        }
        57 => {
            let opts = r.json()?;
            Dispatched { id: 0, result: c.set_shadow_options(&opts) }
        }
        58 => {
            let world = r.f32s()?;
            let yfov = r.f32()?;
            let znear = r.f32()?;
            let zfar = r.f32()?;
            Dispatched { id: 0, result: c.set_camera(&world, yfov, znear, zfar) }
        }
        59 => {
            let direction = r.f32s()?;
            let color = r.f32s()?;
            let intensity = r.f32()?;
            Dispatched { id: 0, result: c.set_sun(&direction, &color, intensity) }
        }
        60 => {
            let sky = r.f32s()?;
            let ground = r.f32s()?;
            Dispatched { id: 0, result: c.set_hemisphere_irradiance(&sky, &ground) }
        }
        61 => {
            let irradiance = r.f32s()?;
            let depth = r.f32s()?;
            let params = r.f32s()?;
            Dispatched { id: 0, result: c.set_gi_probes(&irradiance, &depth, &params) }
        }
        62 => {
            Dispatched { id: 0, result: c.clear_gi_probes() }
        }
        63 => {
            let mode = r.u32()?;
            let color = r.f32s()?;
            let near = r.f32()?;
            let far = r.f32()?;
            let density = r.f32()?;
            Dispatched { id: 0, result: c.set_fog(mode, &color, near, far, density) }
        }
        64 => {
            let sh = r.f32s()?;
            let intensity = r.f32()?;
            Dispatched { id: 0, result: c.set_environment_sh(&sh, intensity) }
        }
        65 => {
            Dispatched { id: 0, result: c.clear_environment() }
        }
        66 => {
            let size = r.u32()?;
            let faces = r.u8s()?;
            let srgb = r.bool()?;
            let intensity = r.f32()?;
            Dispatched { id: 0, result: c.set_background_cube(size, &faces, srgb, intensity) }
        }
        67 => {
            let width = r.u32()?;
            let height = r.u32()?;
            let rgba = r.u8s()?;
            let srgb = r.bool()?;
            let equirect = r.bool()?;
            let intensity = r.f32()?;
            Dispatched { id: 0, result: c.set_background_texture(width, height, &rgba, srgb, equirect, intensity) }
        }
        68 => {
            Dispatched { id: 0, result: c.clear_background_texture() }
        }
        69 => {
            let mode = r.u32()?;
            Dispatched { id: 0, result: c.set_tone_mapping(mode) }
        }
        70 => {
            let e = r.f32()?;
            Dispatched { id: 0, result: c.set_exposure(e) }
        }
        71 => {
            let strength = r.f32()?;
            let radius = r.f32()?;
            let threshold = r.f32()?;
            let smooth_width = r.f32()?;
            Dispatched { id: 0, result: c.set_bloom(strength, radius, threshold, smooth_width) }
        }
        72 => {
            let on = r.bool()?;
            let radius = r.f32()?;
            let thickness = r.f32()?;
            let samples = r.f32()?;
            let distance_exponent = r.f32()?;
            let distance_fall_off = r.f32()?;
            let scale = r.f32()?;
            let resolution_scale = r.f32()?;
            let intensity = r.f32()?;
            let fade_start = r.f32()?;
            let fade_end = r.f32()?;
            Dispatched { id: 0, result: c.set_gtao(on, radius, thickness, samples, distance_exponent, distance_fall_off, scale, resolution_scale, intensity, fade_start, fade_end) }
        }
        73 => {
            let m = r.f32s()?;
            Dispatched { id: 0, result: c.set_color_grade(&m) }
        }
        74 => {
            let on = r.bool()?;
            let mul = r.f32()?;
            Dispatched { id: 0, result: c.set_auto_exposure(on, mul) }
        }
        75 => {
            let rgb = r.f32s()?;
            Dispatched { id: 0, result: c.set_background_color(&rgb) }
        }
        76 => {
            let rgba = r.f32s()?;
            Dispatched { id: 0, result: c.set_clear_color(&rgba) }
        }
        77 => {
            let packed = r.f32s()?;
            Dispatched { id: 0, result: c.set_point_lights(&packed) }
        }
        78 => {
            let packed = r.f32s()?;
            Dispatched { id: 0, result: c.set_extra_dirs(&packed) }
        }
        79 => {
            let h = r.u32()?;
            Dispatched { id: 0, result: c.set_render_height(h) }
        }
        80 => {
            Dispatched { id: 0, result: c.frame_commit() }
        }
        _ => return Err(DecodeError::UnknownOp(op)),
    })
}

/// Every query once, keyed by JS name (the frame-commit report's `q` object).
pub fn collect_queries<C: Commands + ?Sized>(c: &mut C) -> serde_json::Map<String, serde_json::Value> {
    let mut m = serde_json::Map::new();
    m.insert("compressedStats".into(), c.compressed_stats());
    m.insert("threeSkipped".into(), c.three_skipped());
    m.insert("drawnInstanceCount".into(), c.drawn_instance_count());
    m.insert("instanceCount".into(), c.instance_count());
    m.insert("lastGroupHidden".into(), c.last_group_hidden());
    m.insert("shadowStats".into(), c.shadow_stats());
    m.insert("autoExposureGrid".into(), c.auto_exposure_grid());
    m.insert("hdrScene".into(), c.hdr_scene());
    m.insert("passStats".into(), c.pass_stats());
    m.insert("drawCalls".into(), c.draw_calls());
    m.insert("hasTimestamps".into(), c.has_timestamps());
    m.insert("sizes".into(), c.sizes());
    m
}
