// @generated by tools/gen-render-native.mjs from client-rs/packages/render-wasm/src/lib.rs — DO NOT EDIT (bun tools/gen-render-native.mjs)
// Method surface == render-wasm GaiaRender (names + argument order). Wire spec: crates/gaia-render-host/README.md · native-wire.js.
export const API_HASH = 0x97cbae0a;
export const OP_FRAME_COMMIT = 85;
export const OPS = Object.freeze({
  createMesh: 1,
  destroyMesh: 2,
  createSkin: 3,
  setSkinPose: 4,
  destroySkin: 5,
  createSkinnedMesh: 6,
  destroySkinnedMesh: 7,
  createTexture: 8,
  createTextureCompressed: 9,
  createTextureLinear: 10,
  createTextureArray: 11,
  createTextureCube: 12,
  updateTextureLayer: 13,
  setMaterialMaps: 14,
  setMeshUv1: 15,
  setMeshColors: 16,
  setMaterialFlags: 17,
  setMaterialUnlitToneMapped: 18,
  setMaterialNoReceiveShadow: 19,
  setMaterialNoGi: 20,
  setMaterialChrLight: 21,
  setMaterialNoFog: 22,
  setMaterialNoColorWrite: 23,
  setMaterialNoDepthTest: 24,
  setMaterialShadowCullBack: 25,
  destroyTexture: 26,
  createMaterial: 27,
  updateMaterial: 28,
  createShaderMaterial: 29,
  createThreeMaterial: 30,
  createStorageBuffer: 31,
  updateStorageBuffer: 32,
  destroyStorageBuffer: 33,
  bindThreeStorage: 34,
  setThreeTime: 35,
  setThreeUniforms: 36,
  setThreeUniformsBatch: 37,
  setMeshAttribute: 38,
  setInstanceAttribute: 39,
  destroyMaterial: 40,
  createInstance: 41,
  updateInstance: 42,
  removeInstance: 43,
  createInstanceBlock: 44,
  updateInstanceBlock: 45,
  setInstanceBlockUvs: 46,
  setInstanceBlockFlags: 47,
  setInstanceBlockShadowOnly: 48,
  setInstanceBlockDynamic: 49,
  removeInstanceBlock: 50,
  setInstanceStatic: 51,
  setInstanceGroups: 52,
  setInstanceGroupParent: 53,
  setActiveGroups: 54,
  clearActiveGroups: 55,
  setInstanceShadowOnly: 56,
  setInstanceCastShadow: 57,
  setShadowOptions: 58,
  setCamera: 59,
  setSun: 60,
  setHemisphereIrradiance: 61,
  setGiProbes: 62,
  clearGiProbes: 63,
  giComputeInit: 64,
  giComputeVoxels: 65,
  giComputeStep: 66,
  giComputeDestroy: 67,
  setFog: 68,
  setEnvironmentSh: 69,
  clearEnvironment: 70,
  setBackgroundCube: 71,
  setBackgroundTexture: 72,
  clearBackgroundTexture: 73,
  setToneMapping: 74,
  setExposure: 75,
  setBloom: 76,
  setGtao: 77,
  setColorGrade: 78,
  setAutoExposure: 79,
  setBackgroundColor: 80,
  setClearColor: 81,
  setPointLights: 82,
  setExtraDirs: 83,
  setRenderHeight: 84,
  render: 85,
});
export const QUERIES = Object.freeze({
  compressedStats: { drain: false, type: "u32", dflt: [0,0,0,0,0,0] },
  threeSkipped: { drain: false, type: null, dflt: 0 },
  dynBlockStats: { drain: false, type: "u32", dflt: [0,0,0,0,0,0,0] },
  drawnInstanceCount: { drain: false, type: null, dflt: 0 },
  instanceCount: { drain: false, type: null, dflt: 0 },
  lastGroupHidden: { drain: false, type: null, dflt: 0 },
  shadowStats: { drain: false, type: null, dflt: {"enabled":false} },
  giComputeStats: { drain: false, type: "f32", dflt: [0,0,0,0,0,0,0] },
  autoExposureGrid: { drain: true, type: "f32", dflt: [] },
  hdrScene: { drain: false, type: null, dflt: false },
  passStats: { drain: false, type: "u32", dflt: [] },
  drawCalls: { drain: false, type: null, dflt: 0 },
  hasTimestamps: { drain: false, type: null, dflt: false },
  sizes: { drain: false, type: "f32", dflt: [0,0,0,0] },
});

/** rt = { w: Writer, alloc(kind) -> id, q(name) -> cached query value }. */
export class GaiaRenderNativeGen {
  constructor(rt) { this._rt = rt; }
  createMesh(positions, normals, uvs, indices) {
    const id = this._rt.alloc("mesh");
    const w = this._rt.w; w.begin(1);
    w.u32(id);
    w.f32s(positions);
    w.f32s(normals);
    w.f32s(uvs);
    w.u32s(indices);
    w.end();
    return id;
  }
  destroyMesh(id) {
    const w = this._rt.w; w.begin(2);
    w.u32(id);
    w.end();
  }
  createSkin(jointCount, inverseBind) {
    const id = this._rt.alloc("skin");
    const w = this._rt.w; w.begin(3);
    w.u32(id);
    w.u32(jointCount);
    w.f32s(inverseBind);
    w.end();
    return id;
  }
  setSkinPose(id, jointMatrices) {
    const w = this._rt.w; w.begin(4);
    w.u32(id);
    w.f32s(jointMatrices);
    w.end();
  }
  destroySkin(id) {
    const w = this._rt.w; w.begin(5);
    w.u32(id);
    w.end();
  }
  createSkinnedMesh(skin, positions, normals, uvs, joints, weights, indices) {
    const id = this._rt.alloc("mesh");
    const w = this._rt.w; w.begin(6);
    w.u32(id);
    w.u32(skin);
    w.f32s(positions);
    w.f32s(normals);
    w.f32s(uvs);
    w.u32s(joints);
    w.f32s(weights);
    w.u32s(indices);
    w.end();
    return id;
  }
  destroySkinnedMesh(id) {
    const w = this._rt.w; w.begin(7);
    w.u32(id);
    w.end();
  }
  createTexture(width, height, rgba) {
    const id = this._rt.alloc("texture");
    const w = this._rt.w; w.begin(8);
    w.u32(id);
    w.u32(width);
    w.u32(height);
    w.u8s(rgba);
    w.end();
    return id;
  }
  createTextureCompressed(glFormat, width, height, mipCount, data, srgb, flipY) {
    const id = this._rt.alloc("texture");
    const w = this._rt.w; w.begin(9);
    w.u32(id);
    w.u32(glFormat);
    w.u32(width);
    w.u32(height);
    w.u32(mipCount);
    w.u8s(data);
    w.bool(srgb);
    w.bool(flipY);
    w.end();
    return id;
  }
  createTextureLinear(width, height, rgba) {
    const id = this._rt.alloc("texture");
    const w = this._rt.w; w.begin(10);
    w.u32(id);
    w.u32(width);
    w.u32(height);
    w.u8s(rgba);
    w.end();
    return id;
  }
  createTextureArray(width, height, layers, rgba, srgb) {
    const id = this._rt.alloc("texture");
    const w = this._rt.w; w.begin(11);
    w.u32(id);
    w.u32(width);
    w.u32(height);
    w.u32(layers);
    w.u8s(rgba);
    w.bool(srgb);
    w.end();
    return id;
  }
  createTextureCube(size, faces, srgb) {
    const id = this._rt.alloc("texture");
    const w = this._rt.w; w.begin(12);
    w.u32(id);
    w.u32(size);
    w.u8s(faces);
    w.bool(srgb);
    w.end();
    return id;
  }
  updateTextureLayer(id, layer, rgba) {
    const w = this._rt.w; w.begin(13);
    w.u32(id);
    w.u32(layer);
    w.u8s(rgba);
    w.end();
  }
  setMaterialMaps(id, array, normal, roughness, metalness, emissive, ao, normalScale, side) {
    const w = this._rt.w; w.begin(14);
    w.u32(id);
    w.u32(array);
    w.u32(normal);
    w.u32(roughness);
    w.u32(metalness);
    w.u32(emissive);
    w.u32(ao);
    w.f32(normalScale);
    w.u32(side);
    w.end();
  }
  setMeshUv1(id, uv1) {
    const w = this._rt.w; w.begin(15);
    w.u32(id);
    w.f32s(uv1);
    w.end();
  }
  setMeshColors(id, rgba) {
    const w = this._rt.w; w.begin(16);
    w.u32(id);
    w.f32s(rgba);
    w.end();
  }
  setMaterialFlags(id, blend, unlit, depthWrite, renderOrder, castShadow) {
    const w = this._rt.w; w.begin(17);
    w.u32(id);
    w.u32(blend);
    w.bool(unlit);
    w.i32(depthWrite);
    w.i32(renderOrder);
    w.i32(castShadow);
    w.end();
  }
  setMaterialUnlitToneMapped(id, on) {
    const w = this._rt.w; w.begin(18);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  setMaterialNoReceiveShadow(id, on) {
    const w = this._rt.w; w.begin(19);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  setMaterialNoGi(id, on) {
    const w = this._rt.w; w.begin(20);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  setMaterialChrLight(id, on) {
    const w = this._rt.w; w.begin(21);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  setMaterialNoFog(id, on) {
    const w = this._rt.w; w.begin(22);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  setMaterialNoColorWrite(id, on) {
    const w = this._rt.w; w.begin(23);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  setMaterialNoDepthTest(id, on) {
    const w = this._rt.w; w.begin(24);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  setMaterialShadowCullBack(id, on) {
    const w = this._rt.w; w.begin(25);
    w.u32(id);
    w.bool(on);
    w.end();
  }
  destroyTexture(id) {
    const w = this._rt.w; w.begin(26);
    w.u32(id);
    w.end();
  }
  createMaterial(baseColor, metallic, roughness, baseColorTexture, alphaCutoff, emissive) {
    const id = this._rt.alloc("material");
    const w = this._rt.w; w.begin(27);
    w.u32(id);
    w.f32s(baseColor);
    w.f32(metallic);
    w.f32(roughness);
    w.u32(baseColorTexture);
    w.f32(alphaCutoff);
    w.f32s(emissive);
    w.end();
    return id;
  }
  updateMaterial(id, baseColor, metallic, roughness, baseColorTexture, alphaCutoff, emissive) {
    const w = this._rt.w; w.begin(28);
    w.u32(id);
    w.f32s(baseColor);
    w.f32(metallic);
    w.f32(roughness);
    w.u32(baseColorTexture);
    w.f32(alphaCutoff);
    w.f32s(emissive);
    w.end();
  }
  createShaderMaterial(wgsl, vertexEntry, fragmentEntry, bindings) {
    const id = this._rt.alloc("material");
    const w = this._rt.w; w.begin(29);
    w.u32(id);
    w.str(wgsl);
    w.str(vertexEntry);
    w.str(fragmentEntry);
    w.bindings(bindings);
    w.end();
    return id;
  }
  createThreeMaterial(packageJson, textureNames, textureIds) {
    const id = this._rt.alloc("material");
    const w = this._rt.w; w.begin(30);
    w.u32(id);
    w.str(packageJson);
    w.strlist(textureNames);
    w.u32s(textureIds);
    w.end();
    return id;
  }
  createStorageBuffer(bytes) {
    const id = this._rt.alloc("storage");
    const w = this._rt.w; w.begin(31);
    w.u32(id);
    w.u8s(bytes);
    w.end();
    return id;
  }
  updateStorageBuffer(id, bytes) {
    const w = this._rt.w; w.begin(32);
    w.u32(id);
    w.u8s(bytes);
    w.end();
  }
  destroyStorageBuffer(id) {
    const w = this._rt.w; w.begin(33);
    w.u32(id);
    w.end();
  }
  bindThreeStorage(material, key, id) {
    const w = this._rt.w; w.begin(34);
    w.u32(material);
    w.str(key);
    w.u32(id);
    w.end();
  }
  setThreeTime(seconds) {
    const w = this._rt.w; w.begin(35);
    w.f32(seconds);
    w.end();
  }
  setThreeUniforms(material, json) {
    const w = this._rt.w; w.begin(36);
    w.u32(material);
    w.str(json);
    w.end();
    return 0;
  }
  setThreeUniformsBatch(json) {
    const w = this._rt.w; w.begin(37);
    w.str(json);
    w.end();
    return 0;
  }
  setMeshAttribute(mesh, name, itemSize, data) {
    const w = this._rt.w; w.begin(38);
    w.u32(mesh);
    w.str(name);
    w.u32(itemSize);
    w.f32s(data);
    w.end();
  }
  setInstanceAttribute(instance, name, itemSize, data) {
    const w = this._rt.w; w.begin(39);
    w.u32(instance);
    w.str(name);
    w.u32(itemSize);
    w.f32s(data);
    w.end();
  }
  destroyMaterial(id) {
    const w = this._rt.w; w.begin(40);
    w.u32(id);
    w.end();
  }
  createInstance(mesh, material, mat4) {
    const id = this._rt.alloc("instance");
    const w = this._rt.w; w.begin(41);
    w.u32(id);
    w.u32(mesh);
    w.u32(material);
    w.f32s(mat4);
    w.end();
    return id;
  }
  updateInstance(id, mat4) {
    const w = this._rt.w; w.begin(42);
    w.u32(id);
    w.f32s(mat4);
    w.end();
  }
  removeInstance(id) {
    const w = this._rt.w; w.begin(43);
    w.u32(id);
    w.end();
  }
  createInstanceBlock(mesh, material, mats, colors, colorStride, count, world) {
    const id = this._rt.alloc("instance block");
    const w = this._rt.w; w.begin(44);
    w.u32(id);
    w.u32(mesh);
    w.u32(material);
    w.f32s(mats);
    w.f32s(colors);
    w.u32(colorStride);
    w.u32(count);
    w.f32s(world);
    w.end();
    return id;
  }
  updateInstanceBlock(id, mats, colors, colorStride, count, world) {
    const w = this._rt.w; w.begin(45);
    w.u32(id);
    w.f32s(mats);
    w.f32s(colors);
    w.u32(colorStride);
    w.u32(count);
    w.f32s(world);
    w.end();
  }
  setInstanceBlockUvs(id, uvs) {
    const w = this._rt.w; w.begin(46);
    w.u32(id);
    w.f32s(uvs);
    w.end();
  }
  setInstanceBlockFlags(id, castShadow, isStatic) {
    const w = this._rt.w; w.begin(47);
    w.u32(id);
    w.bool(castShadow);
    w.bool(isStatic);
    w.end();
  }
  setInstanceBlockShadowOnly(id, only) {
    const w = this._rt.w; w.begin(48);
    w.u32(id);
    w.bool(only);
    w.end();
  }
  setInstanceBlockDynamic(id, mode) {
    const w = this._rt.w; w.begin(49);
    w.u32(id);
    w.u32(mode);
    w.end();
  }
  removeInstanceBlock(id) {
    const w = this._rt.w; w.begin(50);
    w.u32(id);
    w.end();
  }
  setInstanceStatic(id, isStatic) {
    const w = this._rt.w; w.begin(51);
    w.u32(id);
    w.bool(isStatic);
    w.end();
  }
  setInstanceGroups(id, words) {
    const w = this._rt.w; w.begin(52);
    w.u32(id);
    w.u32s(words);
    w.end();
  }
  setInstanceGroupParent(id, parent) {
    const w = this._rt.w; w.begin(53);
    w.u32(id);
    w.u32(parent);
    w.end();
  }
  setActiveGroups(words) {
    const w = this._rt.w; w.begin(54);
    w.u32s(words);
    w.end();
  }
  clearActiveGroups() {
    const w = this._rt.w; w.begin(55);
    w.end();
  }
  setInstanceShadowOnly(id, only) {
    const w = this._rt.w; w.begin(56);
    w.u32(id);
    w.bool(only);
    w.end();
  }
  setInstanceCastShadow(id, cast) {
    const w = this._rt.w; w.begin(57);
    w.u32(id);
    w.bool(cast);
    w.end();
  }
  setShadowOptions(opts) {
    const w = this._rt.w; w.begin(58);
    w.json(opts);
    w.end();
  }
  setCamera(world, yfov, znear, zfar) {
    const w = this._rt.w; w.begin(59);
    w.f32s(world);
    w.f32(yfov);
    w.f32(znear);
    w.f32(zfar);
    w.end();
  }
  setSun(direction, color, intensity) {
    const w = this._rt.w; w.begin(60);
    w.f32s(direction);
    w.f32s(color);
    w.f32(intensity);
    w.end();
  }
  setHemisphereIrradiance(sky, ground) {
    const w = this._rt.w; w.begin(61);
    w.f32s(sky);
    w.f32s(ground);
    w.end();
  }
  setGiProbes(irradiance, depth, params) {
    const w = this._rt.w; w.begin(62);
    w.f32s(irradiance);
    w.f32s(depth);
    w.f32s(params);
    w.end();
  }
  clearGiProbes() {
    const w = this._rt.w; w.begin(63);
    w.end();
  }
  giComputeInit(cfgJson) {
    const w = this._rt.w; w.begin(64);
    w.str(cfgJson);
    w.end();
  }
  giComputeVoxels(start, words) {
    const w = this._rt.w; w.begin(65);
    w.u32(start);
    w.u32s(words);
    w.end();
  }
  giComputeStep(frame, fresh) {
    const w = this._rt.w; w.begin(66);
    w.f32s(frame);
    w.u32s(fresh);
    w.end();
  }
  giComputeDestroy() {
    const w = this._rt.w; w.begin(67);
    w.end();
  }
  setFog(mode, color, near, far, density) {
    const w = this._rt.w; w.begin(68);
    w.u32(mode);
    w.f32s(color);
    w.f32(near);
    w.f32(far);
    w.f32(density);
    w.end();
  }
  setEnvironmentSh(sh, intensity) {
    const w = this._rt.w; w.begin(69);
    w.f32s(sh);
    w.f32(intensity);
    w.end();
  }
  clearEnvironment() {
    const w = this._rt.w; w.begin(70);
    w.end();
  }
  setBackgroundCube(size, faces, srgb, intensity) {
    const w = this._rt.w; w.begin(71);
    w.u32(size);
    w.u8s(faces);
    w.bool(srgb);
    w.f32(intensity);
    w.end();
  }
  setBackgroundTexture(width, height, rgba, srgb, equirect, intensity) {
    const w = this._rt.w; w.begin(72);
    w.u32(width);
    w.u32(height);
    w.u8s(rgba);
    w.bool(srgb);
    w.bool(equirect);
    w.f32(intensity);
    w.end();
  }
  clearBackgroundTexture() {
    const w = this._rt.w; w.begin(73);
    w.end();
  }
  setToneMapping(mode) {
    const w = this._rt.w; w.begin(74);
    w.u32(mode);
    w.end();
  }
  setExposure(e) {
    const w = this._rt.w; w.begin(75);
    w.f32(e);
    w.end();
  }
  setBloom(strength, radius, threshold, smoothWidth) {
    const w = this._rt.w; w.begin(76);
    w.f32(strength);
    w.f32(radius);
    w.f32(threshold);
    w.f32(smoothWidth);
    w.end();
  }
  setGtao(on, radius, thickness, samples, distanceExponent, distanceFallOff, scale, resolutionScale, intensity, fadeStart, fadeEnd) {
    const w = this._rt.w; w.begin(77);
    w.bool(on);
    w.f32(radius);
    w.f32(thickness);
    w.f32(samples);
    w.f32(distanceExponent);
    w.f32(distanceFallOff);
    w.f32(scale);
    w.f32(resolutionScale);
    w.f32(intensity);
    w.f32(fadeStart);
    w.f32(fadeEnd);
    w.end();
  }
  setColorGrade(m) {
    const w = this._rt.w; w.begin(78);
    w.f32s(m);
    w.end();
  }
  setAutoExposure(on, mul) {
    const w = this._rt.w; w.begin(79);
    w.bool(on);
    w.f32(mul);
    w.end();
  }
  setBackgroundColor(rgb) {
    const w = this._rt.w; w.begin(80);
    w.f32s(rgb);
    w.end();
  }
  setClearColor(rgba) {
    const w = this._rt.w; w.begin(81);
    w.f32s(rgba);
    w.end();
  }
  setPointLights(packed) {
    const w = this._rt.w; w.begin(82);
    w.f32s(packed);
    w.end();
    return Math.min((packed.length / 9) | 0, 64);
  }
  setExtraDirs(packed) {
    const w = this._rt.w; w.begin(83);
    w.f32s(packed);
    w.end();
    return Math.min((packed.length / 7) | 0, 4);
  }
  setRenderHeight(h) {
    const w = this._rt.w; w.begin(84);
    w.u32(h);
    w.end();
  }
  compressedStats() { return this._rt.q("compressedStats"); }
  threeSkipped() { return this._rt.q("threeSkipped"); }
  dynBlockStats() { return this._rt.q("dynBlockStats"); }
  drawnInstanceCount() { return this._rt.q("drawnInstanceCount"); }
  instanceCount() { return this._rt.q("instanceCount"); }
  lastGroupHidden() { return this._rt.q("lastGroupHidden"); }
  shadowStats() { return this._rt.q("shadowStats"); }
  giComputeStats() { return this._rt.q("giComputeStats"); }
  autoExposureGrid() { return this._rt.q("autoExposureGrid"); }
  hdrScene() { return this._rt.q("hdrScene"); }
  passStats() { return this._rt.q("passStats"); }
  drawCalls() { return this._rt.q("drawCalls"); }
  hasTimestamps() { return this._rt.q("hasTimestamps"); }
  sizes() { return this._rt.q("sizes"); }
}
