// GAIA Timeline P2 — authored event document; F8 toggles the witness/editor.
export function register(ctx) {
  const timeline = new Timeline(ctx);
  return { name: 'timeline', api: timeline, update: () => timeline.update() };
}

class Timeline {
  constructor(ctx) {
    this.ctx = ctx; this.zoom = 9; this.offset = 0; this.open = false;
    this.drag = null; this.lastT = this.time(); this.prevEventT = this.lastT;
    this.hooked = null; this.inspected = null; this.firedEvents = 0;
    this.doc = { id: 'gaia-timeline', duration: 30, tracks: [] };
    this.mount(); this.unlisten = ctx.store?.onChange?.((e) => this.recordWorld(e));
    for (const id of ctx.store?.entities?.keys?.() ?? []) this.recordWorld({ kind: 'snapshot', id });
  }
  mount() {
    const style = document.createElement('style'); style.textContent = `
#gaia-timeline-toggle{position:fixed;right:14px;bottom:14px;z-index:31;border:1px solid #58657b;border-radius:4px;background:#182131;color:#dce7f5;padding:6px 9px;font:12px system-ui;cursor:pointer}#gaia-timeline{position:fixed;left:14px;right:14px;bottom:48px;height:330px;z-index:30;display:none;flex-direction:column;background:#101827ef;border:1px solid #3d4d66;border-radius:6px;box-shadow:0 12px 32px #0009;color:#dce7f5;font:12px system-ui;overflow:hidden;backdrop-filter:blur(8px)}#gaia-timeline.open{display:flex}.gt-head{height:34px;display:flex;align-items:center;gap:8px;padding:0 10px;border-bottom:1px solid #34425a}.gt-head button{background:#202d40;border:1px solid #4e607c;border-radius:3px;color:inherit;cursor:pointer}.gt-track{overflow:auto;flex:1;position:relative}.gt-ruler{height:28px;position:sticky;top:0;z-index:4;background:#151f2f;border-bottom:1px solid #34425a;min-width:100%}.gt-tick{position:absolute;top:0;height:100%;border-left:1px solid #52617a;color:#aabbd2;padding:4px}.gt-lane{height:38px;min-width:100%;position:relative;border-bottom:1px solid #26334a;background:linear-gradient(90deg,#131d2c,#111a27)}.gt-label{position:sticky;left:0;z-index:3;display:inline-flex;align-items:center;width:150px;height:38px;padding-left:10px;background:#182335;border-right:1px solid #3d4c66;cursor:pointer}.gt-clip,.gt-marker{position:absolute;cursor:pointer;box-sizing:border-box}.gt-clip{top:8px;height:22px;border:1px solid #7d9fd0;border-radius:3px;background:#315682bb;overflow:hidden;white-space:nowrap;padding:3px 5px}.gt-marker{top:3px;width:3px;height:32px;background:#ffd166;touch-action:none}.gt-marker::after{content:'';position:absolute;top:0;left:-3px;border-left:4px solid transparent;border-right:4px solid transparent;border-top:6px solid #ffd166}.gt-marker::before{content:attr(data-name);position:absolute;left:5px;top:9px;color:#ffe6a0;font:10px system-ui;white-space:nowrap;text-shadow:1px 1px #000}.gt-marker.dragging{background:#8ee3ff}.gt-playhead{position:absolute;top:0;bottom:0;width:2px;background:#ff5b70;z-index:8;pointer-events:none}.gt-empty{padding:12px;color:#9baeca}`; document.head.append(style);
    this.button = document.createElement('button'); this.button.id = 'gaia-timeline-toggle'; this.button.textContent = '⏱ Timeline (F8)'; this.button.dataset.filmAllow = ''; this.button.onclick = () => this.toggle(); document.body.append(this.button);
    this.el = document.createElement('section'); this.el.id = 'gaia-timeline'; this.el.dataset.filmAllow = '';
    this.el.innerHTML = `<div class="gt-head"><b>Timeline · P2 events</b><button data-z="-">−</button><span class="gt-zoom"></span><button data-z="+">+</button><button data-export>export JSON</button><button data-import>import JSON</button><input data-file type=file accept="application/json" hidden><span class="gt-status"></span></div><div class="gt-track"><div class="gt-ruler"></div><div class="gt-lanes"></div><div class="gt-playhead"></div></div>`;
    document.body.append(this.el); this.track = this.el.querySelector('.gt-track'); this.ruler = this.el.querySelector('.gt-ruler'); this.lanes = this.el.querySelector('.gt-lanes'); this.playhead = this.el.querySelector('.gt-playhead');
    this.el.querySelectorAll('[data-z]').forEach((b) => b.onclick = () => { this.zoom = Math.max(2, Math.min(80, this.zoom * (b.dataset.z === '+' ? 1.45 : .69))); this.render(); });
    this.el.querySelector('[data-export]').onclick = () => this.download(); this.el.querySelector('[data-import]').onclick = () => this.el.querySelector('[data-file]').click(); this.el.querySelector('[data-file]').onchange = (e) => this.importFile(e);
    this.track.addEventListener('pointerdown', (e) => { if (e.target.closest('.gt-label,.gt-clip,.gt-marker')) return; this.drag = { scrub: true }; this.scrubPointer(e); this.track.setPointerCapture(e.pointerId); });
    this.track.addEventListener('pointermove', (e) => { if (this.drag?.scrub) this.scrubPointer(e); });
    this.track.addEventListener('pointerup', () => { if (this.drag?.scrub) this.drag = null; });
    document.addEventListener('keydown', (e) => { if (e.code === 'F8' && !e.repeat && !/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)) { e.preventDefault(); this.toggle(); } });
  }
  time() { const t = window.gaia?.director?.status?.().t; return Number.isFinite(t) ? t : performance.now() / 1000; }
  duration() { return Number(window.gaia?.director?.duration ?? this.doc.duration ?? 30); }
  x(t) { return 150 + this.offset + t * this.zoom; }
  toggle() { this.open = !this.open; this.el.classList.toggle('open', this.open); if (this.open) this.render(); }
  ensureTrack(id, label, kind = 'event', targetRef = null) { let t = this.doc.tracks.find((x) => x.id === id); if (!t) { t = { id, kind, label, targetRef, clips: [], markers: [] }; this.doc.tracks.push(t); } return t; }
  addMarker(track, marker) { if (!Number.isFinite(marker.t) || track.markers.some((m) => m.id === marker.id)) return; track.markers.push({ payload: {}, ...marker }); track.markers.sort((a, b) => a.t - b.t); }
  hookFilm() {
    const host = window.gaia?.director?.director, film = host?.film2; if (host && host !== this.hooked?.host && typeof host.cue === 'function') { const original = host.cue.bind(host), self = this; host.cue = function timelineCue(key, t, at, fn) { self.addMarker(self.ensureTrack('cues:director', 'Director cues'), { id: `cue:${key}`, t: at, name: key, segment: self.segmentAt(at), payload: { key } }); return original(key, t, at, fn); }; this.hooked = { host, film: null }; }
    if (!film || film === this.hooked?.film) return; this.hooked = { ...this.hooked, film };
    for (const rec of film.segs ?? []) { const track = this.ensureTrack(`segment:${rec.id}`, `Event · ${rec.id}`, 'event', { film: rec.id }); this.addMarker(track, { id: `${rec.id}:start`, t: rec.win[0], name: `${rec.id} start`, segment: rec.id, payload: { window: rec.win } }); const noteAt = rec.mod?.noteAt; if (typeof noteAt === 'function') { let last = null; for (let t = rec.win[0]; t < rec.win[1]; t += .25) { let name; try { name = noteAt(t); } catch { break; } if (name && name !== last) this.addMarker(track, { id: `${rec.id}:note:${t.toFixed(2)}`, t, name, segment: rec.id, payload: { source: 'noteAt' } }); last = name; } } }
    const lyrics = film.lyrics ?? host?.lyrics; for (const line of lyrics?.lines ?? []) for (const word of line.words ?? []) { const t = Number(word.t0); this.addMarker(this.ensureTrack('lyrics:words', 'Event · lyrics'), { id: `word:${t}:${word.w}`, t, name: String(word.w ?? 'word'), segment: this.segmentAt(t), payload: { t1: word.t1, line: line.text ?? '' } }); }
  }
  segmentAt(t) { return (this.hooked?.film?.segs ?? []).find((s) => t >= s.win[0] && t <= s.win[1])?.id ?? null; }
  recordWorld(e) { const id = e.id; if (!id) return; const kind = e.kind === 'despawn' ? 'removed' : 'appeared'; const tr = this.ensureTrack(`entity:${id}`, `Entity · ${id}`, 'activation', { entityId: id }); this.addMarker(tr, { id: `${kind}:${id}:${this.time().toFixed(3)}`, t: this.time(), name: kind, segment: this.segmentAt(this.time()), payload: {} }); }
  scrubPointer(e) { const r = this.track.getBoundingClientRect(); const t = Math.max(0, Math.min(this.duration(), (e.clientX - r.left + this.track.scrollLeft - 150 - this.offset) / this.zoom)); window.gaia?.director?.scrub?.(t, { resume: false }); this.lastT = t; this.renderPlayhead(t); }
  markerDrag(e, track, marker, el) { e.preventDefault(); e.stopPropagation(); this.drag = { marker, track, el, moved: false }; el.classList.add('dragging'); el.setPointerCapture(e.pointerId); const move = (ev) => { if (!this.drag?.marker) return; const r = this.track.getBoundingClientRect(); marker.t = Math.max(0, Math.min(this.duration(), (ev.clientX - r.left + this.track.scrollLeft - 150 - this.offset) / this.zoom)); this.drag.moved = true; el.style.left = `${this.x(marker.t)}px`; this.publish(marker); }; const end = () => { if (!this.drag?.marker) return; el.classList.remove('dragging'); const moved = this.drag.moved; this.drag = null; if (moved) { track.markers.sort((a, b) => a.t - b.t); this.render(); } }; el.addEventListener('pointermove', move); el.addEventListener('pointerup', end, { once: true }); el.addEventListener('pointercancel', end, { once: true }); }
  anchor() { return this.ctx.store?.entities?.keys?.().next?.().value ?? null; }
  publish(marker) { const id = this.anchor(), store = this.ctx.store, panel = window.gaia?.panel; if (!id || !store?.get || !panel) return; const entity = store.get(id); if (!entity) return; entity.timeline = { id: marker.id, t: marker.t, name: marker.name, segment: marker.segment ?? null, payload: structuredClone(marker.payload ?? {}), idempotent: !!marker.idempotent }; this.inspected = { entityId: id, marker }; if (window.gaia?.editor?.select) window.gaia.editor.select(id); else panel.show(id); }
  syncInspector() { const s = this.inspected, store = this.ctx.store; if (!s || !store?.get) return; const v = store.get(s.entityId)?.timeline; if (!v || v.id !== s.marker.id) return; const t = Number(v.t); if (Number.isFinite(t) && t !== s.marker.t) { s.marker.t = Math.max(0, t); s.marker.name = String(v.name ?? s.marker.name); s.marker.segment = v.segment ?? s.marker.segment; s.marker.payload = structuredClone(v.payload ?? s.marker.payload); s.marker.idempotent = !!v.idempotent; this.render(); } }
  lane(track) { const row = document.createElement('div'); row.className = 'gt-lane'; const lab = document.createElement('span'); lab.className = 'gt-label'; lab.textContent = track.label; row.append(lab); for (const c of track.clips ?? []) { const el = document.createElement('div'); el.className = 'gt-clip'; el.style.left = `${this.x(c.start)}px`; el.style.width = `${Math.max(8, c.duration * this.zoom)}px`; el.textContent = c.id; el.onclick = () => this.publish({ id: c.id, t: c.start, name: c.id, segment: track.targetRef?.film, payload: c.payload ?? {} }); row.append(el); } for (const m of track.markers ?? []) { const el = document.createElement('i'); el.className = 'gt-marker'; el.style.left = `${this.x(m.t)}px`; el.title = `${m.name} @ ${m.t.toFixed(3)}`; el.dataset.name = m.name; el.onpointerdown = (e) => this.markerDrag(e, track, m, el); el.onclick = () => { if (!this.drag) this.publish(m); }; row.append(el); } this.lanes.append(row); }
  renderPlayhead(t) { this.playhead.style.left = `${this.x(t)}px`; }
  render() { if (!this.open) return; const dur = this.duration(), width = this.x(dur) + 80; this.doc.duration = dur; this.ruler.style.width = `${width}px`; this.lanes.style.width = `${width}px`; this.ruler.replaceChildren(); this.lanes.replaceChildren(); for (let t = 0, step = this.zoom < 8 ? 30 : this.zoom < 18 ? 10 : 5; t <= dur; t += step) { const tick = document.createElement('span'); tick.className = 'gt-tick'; tick.style.left = `${this.x(t)}px`; tick.textContent = `${t}s`; this.ruler.append(tick); } const scenes = window.gaia?.director?.scenes ?? []; const chapters = this.ensureTrack('chapters', 'Chapters', 'chapter'); chapters.clips = scenes.map((s) => ({ id: s.id, start: s.t0, duration: s.t1 - s.t0, payload: { note: s.note } })); const rank = (t) => t.id === 'chapters' ? 0 : t.id.startsWith('entity:') ? 2 : 1; for (const t of [...this.doc.tracks].sort((a, b) => rank(a) - rank(b) || a.label.localeCompare(b.label))) this.lane(t); if (!window.gaia?.director) { const empty = document.createElement('div'); empty.className = 'gt-empty'; empty.textContent = 'No director — world-clock entity witness remains available.'; this.lanes.append(empty); } this.el.querySelector('.gt-zoom').textContent = `${this.zoom.toFixed(1)} px/s`; this.el.querySelector('.gt-status').textContent = `${this.doc.tracks.reduce((n, t) => n + t.markers.length, 0)} markers · fired ${this.firedEvents}`; this.renderPlayhead(this.time()); }
  dispatchEvents(prev, t) { if (t < prev) return; for (const track of this.doc.tracks) for (const m of track.markers) if (m.t > prev && m.t <= t && (!this.drag || m.idempotent)) this.firedEvents++; }
  update() { this.hookFilm(); this.syncInspector(); const t = this.time(); this.dispatchEvents(this.prevEventT, t); this.prevEventT = t; if (this.open && (Math.abs(t - this.lastT) > .03 || !this.lanes.childElementCount)) this.render(); this.lastT = t; }
  exportJSON() { return JSON.stringify(this.doc, null, 2); }
  download() { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([this.exportJSON()], { type: 'application/json' })); a.download = 'gaia-timeline.json'; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 0); }
  async importFile(e) { const f = e.target.files?.[0]; if (!f) return; try { const doc = JSON.parse(await f.text()); if (!Array.isArray(doc.tracks)) throw new Error('tracks[] required'); this.doc = doc; this.inspected = null; this.render(); } catch (err) { console.warn('[timeline] import failed', err); } e.target.value = ''; }
  debug() { return { firedEvents: this.firedEvents, doc: JSON.parse(this.exportJSON()) }; }
}
